[project]
name = "semestralka"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "bleach>=6.2.0",
    "django>=5.2.1",
    "django-admin>=2.0.2",
    "mysqlclient>=2.2.7",
]
