# Generated by Django 5.2.1 on 2025-05-30 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeskovaHra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3, 'Název musí mít alespoň 3 znaky.')], verbose_name='Název hry')),
                ('popis', models.TextField(blank=True, help_text='Krátký popis hry (volitelné).', verbose_name='Popis')),
                ('datum_vydani', models.DateField(verbose_name='Datum vydání')),
                ('cena', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Cena (Kč)')),
                ('pocet_hracu', models.IntegerField(verbose_name='Počet hráčů')),
                ('datum_pridani', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
