# Generated by Django 5.2.1 on 2025-06-03 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deskovahra',
            name='cena',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='deskovahra',
            name='nazev',
            field=models.CharField(help_text='Zadejte název deskové hry.', max_length=50, validators=[django.core.validators.MinLengthValidator(3, 'Název musí mít alespoň 3 znaky.')], verbose_name='Název hry'),
        ),
        migrations.AlterField(
            model_name='deskovahra',
            name='popis',
            field=models.TextField(blank=True, help_text='Krátký popis hry.', verbose_name='Popis'),
        ),
    ]
